name: Fuzz Parser

on:
  push:
    branches: [master]
    paths:
      - src/scanner.c
      - src/tree-sitter-typescript/scanner.h
  pull_request:
    paths:
      - src/scanner.c
      - src/tree-sitter-typescript/scanner.h

jobs:
  fuzz:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: tree-sitter/fuzz-action@v4
